pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "your-docker-username/${env.SERVICE_NAME}:${BUILD_NUMBER}"
    }

    stages {
        stage('Clone Repo') {
            steps {
                  git credentialsId: 'github-token', url: 'https://github.com/tanvirmulla11/ecommerce-microservices.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(DOCKER_IMAGE, ".")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-pass', variable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u your-docker-username --password-stdin'
                    sh "docker push $DOCKER_IMAGE"
                }
            }
        }
    }
}
